const mongoose = require("mongoose");

const schoolSchema = new mongoose.Schema({
    schoolNumber: { type: Number, required: true },
    department:{ type: String, enum: ["Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", 
        "Flores", "Florida", "Lavalleja", "Maldonado", "Montevideo", 
        "Paysandú", "Río Negro", "Rivera", "Rocha", "Salto", 
        "San José", "Soriano", "Tacuarembó", "Treinta y Tres"], required: true },
    city:{ type: String, enum: ['Montevideo',
            'Salto',
            'Ciudad de la Costa',
            'Paysandú',
            'Las Piedras',
            'Rivera',
            'Maldonado',
            'Tacuarembó',
            'Melo',
            'Mercedes',
            'Artigas',
            'Minas',
            'San José de Mayo',
            'Durazno',
            'Florida',
            'Barros Blancos',
            'Ciudad del Plata',
            'San Carlos',
            'Colonia del Sacramento',
            'Pando',
            'Treinta y Tres',
            'Rocha',
            'Fray Bentos',
            'Trinidad',
            'La Paz',
            'Canelones',
            'Carmelo',
            'Dolores',
            'Young',
            'Santa Lucía',
            'Progreso',
            'Paso de Carrasco',
            'Río Branco',
            'Paso de los Toros',
            'Juan Lacaze',
            'Bella Unión',
            'Nueva Helvecia',
            'Libertad',
            'Rosario',
            'Nueva Palmira',
            'Chuy',
            'Punta del Este',
            'Piriápolis',
            'Salinas',
            'Parque del Plata',
            'Lascano',
            'Castillos',
            'Tranqueras',
            'Sarandí del Yí',
            'San Ramón',
            'Tarariras',
            'Pan de Azúcar',
            'Sauce',
            'Sarandí Grande',
            'Atlántida',
            'José Pedro Varela',
            'Tala',
            'Guichón',
            'Cardona',
            'San Jacinto',
            'Toledo',
            'Vergara',
            'Santa Rosa',
            'Florencio Sánchez',
            'La Paloma',
            'San Gregorio de Polanco',
            'Ombúes de Lavalle',
            'Colonia Valdense',
            'Rodríguez',
            'Cerrillos',
            'Aiguá',
            'Migues',
            'San Bautista'], required: true },
            address:{ type: String, required: true }
});

module.exports=schoolSchema;